#!/bin/sh

mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs none /dev
mount -t tmpfs none /tmp

echo "Kernel boot time: $(cut -d' ' -f1 /proc/uptime) s"

echo mochi > /proc/sys/kernel/hostname
